name: mitex::ci
on: [push, pull_request]

env:
  RUSTFLAGS: "-Dwarnings"
  RUSTDOCFLAGS: "-Dwarnings"
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"
  CARGO_INCREMENTAL: "0"

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { submodules: recursive }
      - uses: typst-community/setup-typst@v3
        with: { typst-version: "0.10.0" }
      - uses: rui314/setup-mold@v1
      - uses: dtolnay/rust-toolchain@stable
        with: { targets: wasm32-unknown-unknown }
      - uses: mozilla-actions/sccache-action@v0.0.3
      - run: cargo test --workspace --no-fail-fast
  checks:
    name: Check clippy, formatting, and documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { submodules: recursive }
      - uses: typst-community/setup-typst@v3
        with: { typst-version: "0.10.0" }
      - uses: rui314/setup-mold@v1
      - uses: dtolnay/rust-toolchain@stable
        with: { targets: wasm32-unknown-unknown }
      - uses: mozilla-actions/sccache-action@v0.0.3
      - run: cargo clippy --workspace --all-targets --all-features
      - run: cargo fmt --check --all
      - run: cargo doc --workspace --no-deps
  build-wasm-plugin:
    name: Build Wasm modules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { submodules: recursive }
      - uses: typst-community/setup-typst@v3
        with: { typst-version: "0.10.0" }
      - uses: rui314/setup-mold@v1
      - uses: dtolnay/rust-toolchain@stable
        with: { targets: wasm32-unknown-unknown }
      - uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: "v0.12.1"
      - uses: mozilla-actions/sccache-action@v0.0.3
      - run: scripts/build.sh
